theme: jekyll-theme-dinky
title: MEOM's catalog
description: This is where you can find all the informations about the available datasets extracted from simulations performed by MEOM
collections:
  datasets:
    output: true
